### ISSUE TITLE
The codebase is unreadable.

### ISSUE THREAD

**Issue by Heimdell** [ndmitchell/supero#1]
The theme of supercompilation looks interesting for me. 

I tried to parse your code, and I ended in understanding that I must reformat everything in canonical form before I can start dispatching it.

I could make the code more readable for wide auditory, but I need to know two things:
1) what subset of code is alive (supero4 + lib/plugin?)
2) what subset of code is a subject to change in the near future?

The one exceptionaly eye-raping feature used is ViewPatterns (Constr (projection -> result)). Please, refuse to use it. Its really bad thing.

Name-hinding tricks like

``` haskell
(n:ew, ...) <- get
case ... of
    Just n ->
        (expr containing n)

    Nothing ->
        (same expr containing n)
```

are pretty bad. Please, refuse to use it, too.

Whouldn't you mind, if I convert all your "[(a, b)]" dictionaries into "Map a b" ones? It would speed the system up a bit.

I also like to remove `unsafePerformIO` from code (wrapping related things into ReaderT env, for instance).

**Comment by ndmitchell** [comment]
This code is very much my development for supercompilation - it's not intended to necessarily be readable or polished (or even correct). For a more polished account I suggest you read (I'll add these to a readme):
- My ICFP paper http://community.haskell.org/~ndm/downloads/paper-rethinking_supercompilation-29_sep_2010.pdf
- Max's thesis http://www.cl.cam.ac.uk/techreports/UCAM-CL-TR-835.html
- Issue 23 of The Monad Reader: http://themonadreader.wordpress.com/2014/04/23/issue-23/
- SC Mini supercompiler project: https://github.com/ilya-klyuchnikov/sc-mini

The current active work is in the supero4 directory, and the file travis.hs in that directory gives the command lines I use to test it. I'll add a readme clarifying that. I intend to hack on the supero4 directory in the near future, but it's very much dependent on how I feel at the time.

As to the coding style:
- I think view patterns are great, see [my blog post](http://neilmitchell.blogspot.co.uk/2009/11/reviewing-view-patterns.html). That also categorises how I'm using it.
- I often use name hiding to hide names that were in scope but that are now undesirable. For example, in the instance you specified, if I bound the `Just` to `n2`, then I could equally refer to either `n` or `n2` in the case alternative, where one was wrong. By hiding the bad name, I guarantee to hit the right name.
- I am sure I'll convert all the lists to maps at some point, but for the moment it's not been necessary, and lists are simpler. I did benchmark, and lists aren't the hotspot by a long way.
- I seem to barely use `unsafePerformIO` compared to some of my other libraries :) (looking purely at the supero4 directory). I think all the uses are pretty benign.

I do hope to write up the supero4 work, once it's complete, but it needs a lot more research first. When I write it up I might also polish up the code to a releasable state, but I suspect that will be months if not a year.
